import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/global/globals.css"

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: '@/resource/favicon.ico',
}

// https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required

export default function RootLayout( {
    children,
}: {
    children: React.ReactNode
} ) {
    return (
            <html lang="en">
            <body className={ inter.className }>{ children }</body>
            </html>
    )
}
